# -*- coding: utf-8 -*-
"""Regressao_Linear.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H9Gl5GfVxZdlpDRNECtb4ocBLb1wp3MB
"""

import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

iris = load_iris().data

def LR_Normal_eq(x,y):

  xt = np.transpose(x)
  xt_x = np.dot(xt,x)
  xt_y = np.dot(xt,y)

  try:
    theta = np.linalg.solve(xt_x,xt_y)
    return theta
  except np.linalg.LinAlgError:
    return None

x = np.asarray([iris[i][0] for i in range(len(iris))]).reshape(-1,1)
y = np.asarray([iris[i][1] for i in range(len(iris))]).reshape(-1,1)

x_intercept = np.c_[np.ones((x.shape[0], 1)), x]

theta = LR_Normal_eq(x_intercept,y)

theta